
INSERT INTO PRODUCT(PRICE, CATEGORY, NAME)VALUES(200.00, 'ELETRÔNICO', 'IPAD');
INSERT INTO PRODUCT(PRICE, CATEGORY, NAME)VALUES(300.00, 'ELETRÔNICO', 'IPOD');
INSERT INTO PRODUCT(PRICE, CATEGORY, NAME)VALUES(800.00, 'ELETRÔNICO', 'Samsung');
